### ISSUE TITLE
X Error of failed request: BadLength

### ISSUE THREAD

**Issue by Earthcomputer** [zlepper/itlt#27] opened 2021-07-25 10:09 UTC
**Describe the bug**
Mod crashes on startup on Linux (using X11)

**To Reproduce**
1. Launch the game with ITLT installed, on Linux using X11
2. Observe crash

**Expected behavior**
No crash

**Environment details**
Please fill in what you know, skip any parts you don't know.
- Operating system (e.g. Windows 10): Ubuntu 18.04
- Java (e.g. AdoptOpenJDK 8 HotSpot): 
```
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (build 1.8.0_292-8u292-b10-0ubuntu1~18.04-b10)
OpenJDK 64-Bit Server VM (build 25.292-b10, mixed mode)
```
- Mod version (e.g. 1.16.5-2.0.0): 1.16.x-2.0.0
- Minecraft version (e.g. 1.16.5): 1.16.5

**Logs and additional context**
https://paste.ee/p/DFQQ0

This issue was first reported to the modpack [here](https://github.com/Harve/GoCreateModpack/issues/7) and they said it was caused by ITLT

**Comment by PaintNinja** [comment] 2021-09-01 23:48
Hello, thanks for your report.

There have been some improvements to handling the window icon in v2.0.1, please may you retest and see if the issue persists?

If still no luck, would you be willing to try upgrading your Ubuntu version to the latest LTS release (20.04 at the time of writing)?

**Comment by PaintNinja** [comment] 2022-06-01 19:51
Closing as unable to reproduce. If you come across the same issue again on the latest mod version, feel free to write a comment here and I'll re-open.

**Closed as completed by PaintNinja** 2022-06-01 19:51 UTC
Labels: bug
