### ISSUE TITLE
Server compatibility issue

### ISSUE THREAD

**Issue by X-Niter** [zlepper/itlt#17] opened 2020-12-24 23:00 UTC
We tried to add this to both our server and our client due to not being able to join our private server when ever we only had this mod on our client-side pack. 

We know it's not supposed to be on the server but it was worth a shot, that being said, for some reason when you have the mod in our modpack we are not able to join our server and are getting that we are not compatible with the server.

**Comment by PaintNinja** [comment] 2020-12-24 23:08
Hello, please drag and drop the client and server logs (from when a client tries to connect to the server and gets denied) so I can look into this.

**Comment by X-Niter** [comment] 2020-12-25 08:07
Okay, So I tried it again and it looks like I can join but the multiplayer list that pings the server is showing as not compatible.
I don't believe it's registering as client-side so it's doing that.

[latest.log](https://github.com/zlepper/itlt/files/5741478/latest.log)
[latest.log](https://github.com/zlepper/itlt/files/5741479/latest.log)


![image](https://user-images.githubusercontent.com/30506033/103126961-a0ddff80-4655-11eb-8585-4b8de21096ea.png)

**Comment by PaintNinja** [comment] 2020-12-25 13:42
According to your logs, it looks as if these mods are on the server but not the client which might be the cause of the incompatible icons on the multiplayer list:
`[25Dec2020 02:04:04.932] [Netty Client IO #3/INFO] [net.minecraftforge.fml.client.ClientHooks/CLIENTHOOKS]: Server has additional mods that may be needed on the client: structurize@0.13.104-ALPHA, minecolonies@0.13.537-ALPHA`

Could you confirm whether or not this still happens when you either remove those mods server-side or add them client-side?

**Comment by X-Niter** [comment] 2020-12-26 00:05
Oh ooops, I don't know why I sent you that log, that is a completely different log then what was meant to be sent to you. 
I'm attaching a new one now which is the correct one.

To reclarify, I CAN join the server fine, it's just that the multiplayer menu is pinging the server as "Not Compatible" even though it is.

The same issue I had also gotten fixed over on Notes mod, I'll provide the link only as a reference ->
 [Here is the reference to that issue over on notes mod issue tab](https://github.com/MattCzyr/Notes/issues/17)
 
 Here is the exact line from logs on what I am talking about ::
`[25Dec2020 17:51:44.579] [Netty Client IO #0/INFO] [net.minecraftforge.fml.client.ClientHooks/CLIENTHOOKS]: Client has mods that are missing on server: [itlt, world_pre_generator]`

I do apologize in advance if the above messages were vague or unclear. :)

[latest.log](https://github.com/zlepper/itlt/files/5742516/latest.log)

**Comment by PaintNinja** [comment] 2021-01-16 22:32
Should be fixed by b02400f (PR #18), expect an update fairly soon. Thanks for your report and thanks to @kmecpp for the PR! :)

**Closed as completed by PaintNinja** 2021-01-16 22:32 UTC
Labels: bug
