### ISSUE TITLE
Debug log spam

### ISSUE THREAD

**Issue by Treeways** [zlepper/itlt#42] opened 2023-05-09 19:55 UTC
`logs/debug.log` is constantly being spammed by the following lines:

```log
[Render thread/DEBUG] [dk.zlepper.itlt.itlt/]: itltJarPath: /home/username/.local/share/PrismLauncher/instances/instance name/.minecraft/mods/itlt-1.19.x-2.1.5.jar
[Render thread/DEBUG] [dk.zlepper.itlt.itlt/]: instanceName: instance name
```

This happens constantly while in-world, or when alt-tabbing.

I'm running Minecraft 1.19.2, with ITLT 2.1.5 on Fedora Linux 37, with OpenJDK 17.

**Comment by Treeways** [comment] 2023-05-09 19:58
Here's a longer example of what is happening constantly in the log file:

```
[Render thread/DEBUG] [dk.zlepper.itlt.itlt/]: itltJarPath: /home/username/.local/share/PrismLauncher/instances/instance name/.minecraft/mods/itlt-1.19.x-2.1.5.jar
[Render thread/DEBUG] [dk.zlepper.itlt.itlt/]: instanceName: instance name
[Render thread/DEBUG] [dk.zlepper.itlt.itlt/]: itltJarPath: /home/username/.local/share/PrismLauncher/instances/instance name/.minecraft/mods/itlt-1.19.x-2.1.5.jar
[Render thread/DEBUG] [dk.zlepper.itlt.itlt/]: instanceName: instance name
[Render thread/DEBUG] [dk.zlepper.itlt.itlt/]: itltJarPath: /home/username/.local/share/PrismLauncher/instances/instance name/.minecraft/mods/itlt-1.19.x-2.1.5.jar
[Render thread/DEBUG] [dk.zlepper.itlt.itlt/]: instanceName: instance name
[Render thread/DEBUG] [dk.zlepper.itlt.itlt/]: itltJarPath: /home/username/.local/share/PrismLauncher/instances/instance name/.minecraft/mods/itlt-1.19.x-2.1.5.jar
[Render thread/DEBUG] [dk.zlepper.itlt.itlt/]: instanceName: instance name
[Render thread/DEBUG] [dk.zlepper.itlt.itlt/]: itltJarPath: /home/username/.local/share/PrismLauncher/instances/instance name/.minecraft/mods/itlt-1.19.x-2.1.5.jar
[Render thread/DEBUG] [dk.zlepper.itlt.itlt/]: instanceName: instance name
[Render thread/DEBUG] [dk.zlepper.itlt.itlt/]: itltJarPath: /home/username/.local/share/PrismLauncher/instances/instance name/.minecraft/mods/itlt-1.19.x-2.1.5.jar
[Render thread/DEBUG] [dk.zlepper.itlt.itlt/]: instanceName: instance name
[Render thread/DEBUG] [dk.zlepper.itlt.itlt/]: itltJarPath: /home/username/.local/share/PrismLauncher/instances/instance name/.minecraft/mods/itlt-1.19.x-2.1.5.jar
[Render thread/DEBUG] [dk.zlepper.itlt.itlt/]: instanceName: instance name
[Render thread/DEBUG] [dk.zlepper.itlt.itlt/]: itltJarPath: /home/username/.local/share/PrismLauncher/instances/instance name/.minecraft/mods/itlt-1.19.x-2.1.5.jar
[Render thread/DEBUG] [dk.zlepper.itlt.itlt/]: instanceName: instance name
[Server thread/INFO] [net.minecraft.client.server.IntegratedServer/]: Saving and pausing game...
[Render thread/DEBUG] [Tips/]: Displaying tip tipsmod:absolem_joke_tips/provoke on screen PauseScreen.
[Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[World Name]'/minecraft:overworld
[Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[World Name]'/minecraft:the_nether
[Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[World Name]'/minecraft:the_end
[Server thread/DEBUG] [net.minecraftforge.common.ForgeHooks/WP]: Gathering id map for writing to world save World Name
[Server thread/DEBUG] [net.minecraftforge.common.ForgeHooks/WP]: ID Map collection complete World Name
[Render thread/DEBUG] [dk.zlepper.itlt.itlt/]: itltJarPath: /home/username/.local/share/PrismLauncher/instances/instance name/.minecraft/mods/itlt-1.19.x-2.1.5.jar
[Render thread/DEBUG] [dk.zlepper.itlt.itlt/]: instanceName: instance name
[Render thread/DEBUG] [dk.zlepper.itlt.itlt/]: itltJarPath: /home/username/.local/share/PrismLauncher/instances/instance name/.minecraft/mods/itlt-1.19.x-2.1.5.jar
[Render thread/DEBUG] [dk.zlepper.itlt.itlt/]: instanceName: instance name
[Render thread/DEBUG] [dk.zlepper.itlt.itlt/]: itltJarPath: /home/username/.local/share/PrismLauncher/instances/instance name/.minecraft/mods/itlt-1.19.x-2.1.5.jar
[Render thread/DEBUG] [dk.zlepper.itlt.itlt/]: instanceName: instance name
```

**Comment by PaintNinja** [comment] 2023-07-22 17:53
I'm unable to reproduce this. What mods do you have installed?

**Comment by PaintNinja** [comment] 2024-10-07 20:12
Closing due to unable to reproduce and lack of a response for over a year. If this issue persists, please answer my question so that I can figure out the culprit and look into fixing it

**Closed as not planned by PaintNinja** 2024-10-07 20:12 UTC
Labels: bug

**Comment by Treeways** [comment] 2024-10-08 01:14
Whoops, sorry about that! The modpack I was using this mod with has been abandoned, so please disregard this issue.
