### ISSUE TITLE
Pack gets stuck loading when this mod is installed (1.12.2)

### ISSUE THREAD

**Issue by TheComputerizer** [zlepper/itlt#21] opened 2021-04-29 22:59 UTC
I tried adding this mod to my pack, but when loading up, right after it switched the window title, it shows forge loading 6/7 and ModIdMapping - Minecraft Forge and just gets stuck there no matter how long I wait, [like so](https://imgur.com/a/xKTdcgr). I compared with the exact same settings with & without the mod, but it seems this mod is what gets it stuck. [Here](https://pastebin.com/6pBPNQRV) is my config file. I would post my log file too, but its too massive for most pasting sites to handle and did not show any errors relating to itlt.

**Comment by PaintNinja** [comment] 2021-04-30 11:41
I test all built jars outside of the dev env before publishing to make sure that they at least don't crash on launch, so it's odd that you're coming across a hang caused by this mod as I would've noticed that immediately.

Having a log so large that you can't upload it is suspicious and suggests that there may be error spam from other mods, which in turn may impact the stability of the whole game depending on what's going wrong.

While I don't suspect itlt is directly at fault here, I want to make sure regardless so if you could do the following it would be appreciated:
- What version of the mod are you using?
- What version of Forge are you using?
- What operating system are you using and what version? (e.g. Windows 10, MacOS 11.1, etc...)
- Could you split the log uploads into two? (i.e. copy half of it and paste it on a pasting site, then do the same for the other half and send me the two links)

By the way, I noticed in your config you changed the 32bit warning text but didn't actually enable it. ;)

**Comment by TheComputerizer** [comment] 2021-04-30 13:26
Its just because my pack is so big that it generates a big log when starting up. I did change the 32bit warning text, but disabled it in case that was somehow causing the issue (it wasn't)

- The version of the mod is the latest 1.12.2 version itlt-1.12.2-1.0.3
- Forge Version 14.23.5.2854
- OS is Windows 10
- [Log Pt1](https://paste.ubuntu.com/p/YJH3ppZR9n/) - lines 1-10000
- [Log Pt2](https://paste.ubuntu.com/p/C42mV43KJZ/) - lines 10001-15873

A weird thing to note is that if I uninstall the mod, start up the pack fine, then go and reinstall the mod again, it will start up ok the first time and then get stuck every time after that

**Comment by PaintNinja** [comment] 2021-04-30 14:06
Generating nearly 16 thousand lines of logs just starting up the game is not normal, even on big modpacks. Looking at your log, it's filled with errors and warnings that would indicate an unstable environment.

Here's *some* of the errors I found, excluding different errors of the same type (you can CTRL+F through your log to find these):
- `[Client thread/WARN]: Potentially Dangerous alternative prefix "x" for name "y", expected "modName". This could be a intended override, but in most cases indicates a broken mod.`
- `[com.valkyrieofnight.et.m_multiblocks.m_voidminer.registry.json.TargetableJsonHandler:loadRegistryFromJson:47]: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 173 column 8 path $.outputs[34]`
- `[thelm.oredictinit.compat.CompatGalacticraftPlanets:register:52]: java.lang.ClassNotFoundException: micdoodle8.mods.galacticraft.planets.asteroids.items.AsteroidItems`
- `Could not load override model thermalfoundation:item/tool/shield_blocking for model thermalfoundation:models/item/tool/shield
net.minecraftforge.client.model.ModelLoaderRegistry$LoaderException: circular model dependencies, stack: [thermalfoundation:item/tool/shield_gold_blocking, thermalfoundation:item/tool/shield_blocking]`
- `Failed to identify sun.reflect.GeneratedMethodAccessor3 (untransformed name: sun.reflect.GeneratedMethodAccessor3)`
- `Unexpected duplicate pool name 'shader' in table 'twilightforest:entities/minoshroom'. Duplicate added as 'shader0'.
Report this to the loot adder.`
- `Recipe has invalid inputs and will be ignored: net.minecraftforge.oredict.ShapedOreRecipe@539e7fbf (artisanworktables:recipe.artisans_cutters.boron)`
- `Invalid registration attempt for an Ore Dictionary item with name oreArdite has occurred. The registration has been denied to prevent crashes. The mod responsible for the registration needs to correct this.`
- `Cannot add smelting recipe Smelting: Bronze Dust (1xitem.exoplanets.alloydust@0 => 1xitem.thermalfoundation.material@163) because another mod already has registered a recipe 1xitem.exoplanets.alloydust@0 => 1xitem.exoplanets.alloyingot@0.`
- `Couldn't find the processVehicleMove method (or any of its patch targets) to patch :( Please report this`
- `The mod redstoneflux is expecting signature 8a6abf2cb9e141b866580d369ba6548732eff25f for source RedstoneFlux-1.12-2.1.1.1-universal.jar, however there is no signature matching that description`
- `A broken ore dictionary registration with name ingotGaia has occurred. It adds an item (type: class vazkii.botania.common.item.material.ItemManaResource) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod More Plates report it to them!`

If I were you, I would start by updating Forge to the latest build for 1.12.2 and removing coremods (and mods that depend on said coremods) one by one until it works. You can find a list of coremods at line 695 in the log you sent me.

Coremods are mods that modify the game directly, in a way that is not guaranteed to be compatible with other mods unless done with great care. Even then, some properly written coremods may still not play well with other coremods depending on what they're both modifying.

I'm closing this as itlt does not seem to be the cause of the hang here. If you can reproduce this with just itlt on its own in the mods folder or with other specific mods please open a new issue and I'll look into it. Sorry I can't be more helpful :(

**Closed as completed by PaintNinja** 2021-04-30 14:06 UTC
